version: "3.3"
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      # - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  pandoc-client:
    depends_on:
      - pandoc-service
    build:
      dockerfile: Dockerfile
      context: ./frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.pandoc-gijsentius-com-client.rule=Host(`localhost`)

  pandoc-service:
    build:
      dockerfile: Dockerfile
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.pandoc-gijsentius-com-service.rule=Host(`localhost`) && PathPrefix(`/api`)
